version: '3.7'
services:
  database:
    image: "postgres:14.9"
    ports: 
      - "5432:5432"
    env_file:
      - database.env # configure postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/10-init.sql